version: "3"
services:
    db:
      image: mysql:5.6
      container_name: mysql
      volumes:
        - /var/lib/mysql:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=acidbox
        - MYSQL_USER=acidbox
        - MYSQL_PASSWORD=acidbox
      restart: unless-stopped
      ports:
        - 3306:3306
    web:
      image: abiosoft/caddy:php
      container_name: caddy
      volumes:
        - /var/www:/srv
        - /etc/caddy:/etc
      environment:
        - CADDYPATH=/etc/caddycerts
        - ACME_AGREE=true
      restart: unless-stopped
      ports:
        - 80:80
        - 443:443
        - 2015:2015
    photos:
      image: linuxserver/lychee
      container_name: lychee
      volumes:
        - /etc/lychee:/config
        - /var/www/lychee:/pictures
      restart: unless-stopped
      ports:
        - 2500:80
    wordpress:
      image: wordpress
      container_name: wordpress
      links:
        - db:mysql
      environment:
        - WORDPRESS_DB_HOST=db
        - WORDPRESS_DB_USER=acidbox
        - WORDPRESS_DB_PASSWORD=acidbox
        - WORDPRESS_DB_NAME=allofmywork
        - WORDPRESS_TABLE_PREFIX=_blog
      restart: unless-stopped
      ports:
        - 8080:80
    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      links:
        - db:mysql
      environment:
        - MYSQL_USERNAME=root
        - MYSQL_ROOT_PASSWORD=acidbox #changeme
        - PMA_HOST=mysql
      restart: unless-stopped
      ports:
        - 8181:80


      
