version: "3"
services:
    db:
      image: mariadb:latest
      container_name: mysql
      volumes:
        - /opt/acidbox/mysql:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=acidbox
        - MYSQL_DATABASE=wordpress
        - MYSQL_USER=wordpress
        - MYSQL_PASSWORD=wordpress
      restart: unless-stopped
    web:
      image: abiosoft/caddy:php
      container_name: caddy
      volumes:
        - /opt/acidbox/www:/srv
        - /opt/acidbox/caddy/Caddyfile:/etc/Caddyfile
        - /opt/acidbox/caddy/certs:/root/.caddy
      environment:
        - ACME_AGREE=true
      restart: unless-stopped
      ports:
        - 80:80
        - 443:443
        - 2015:2015
    photos:
      image: linuxserver/lychee
      container_name: lychee
      volumes:
        - /opt/acidbox/lychee/config:/config
        - /opt/acidbox/lychee/data:/pictures
      restart: unless-stopped
    wordpress:
      image: wordpress
      container_name: wordpress
      links:
        - db:mysql
      volumes:
        - /opt/acidbox/wordpress:/var/www/html
      environment:
        - WORDPRESS_DB_HOST=db
        - WORDPRESS_DB_USER=wordpress
        - WORDPRESS_DB_PASSWORD=wordpress
        - WORDPRESS_DB_NAME=wordpress
        - WORDPRESS_TABLE_PREFIX=_blog #changeme
      restart: unless-stopped
    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      links:
        - db:mysql
      environment:
        - MYSQL_USERNAME=root
        - MYSQL_ROOT_PASSWORD=acidbox
        - PMA_HOST=mysql
      restart: unless-stopped
    updates:
      image: v2tec/watchtower
      container_name: watchtower
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      restart: always
      command: --interval 30
    management:
      image: portainer/portainer
      container_name: portainer
      volumes:
        - /opt/acidbox/portainer:/data
        - /var/run/docker.sock:/var/run/docker.sock
      restart: always
networks:
  default:
     name: acidbox
